title: clipping path
description: >-
  I haven't had this training since I first started doing photo editing. This is
  the first step of photo editing. I learned something new by thinking that I
  was very happy then. Now I can express many of my thoughts through color
  design.
template:
  repo: clipping-path-template
  name: clipping-path
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
